### ISSUE TITLE
Exclusion filters

### ISSUE THREAD

**Issue by vkruoso** [tandg-digital/objection-filter#44]
Not sure this is the best place to ask.  I'm thinking about negative (or exclusion) filters. Not sure if I'm missing something, but I could not find a way to do it based on the docs.

So the idea is that instead of selecting a huge list of things, I could just negate a small list. This makes a lot of sense in a few scenarios and even helps on the SQL generated, as it is smaller in size and can also be better for the database engine.

Is this supposed to be implemented as a custom filter?

**Comment by jeff3yan** [comment]
Exclusion filters (eg WHERE NOT IN) aren't part of the standard filter set, so yes they would need to be implemented as a custom filter.

However [objection.js/knex](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#wherenotin) has a built in function for that, so it would be straightforward to implement.

Is this what you were after?

**Comment by vkruoso** [comment]
Yeah. To me it makes sense to support this natively in this lib, but can also be implemented as a custom filter as well! Just wanted to understand if that is something we should have as part of the standard filters or not.

If you allow me, I have a another question (feel free to tell if you prefer a new issue): objection supports a [custom query builder](https://vincit.github.io/objection.js/recipes/custom-query-builder.html). It seems that the query generated by the plugin does not consider that. I have a custom query builder that applies one `where(a,b)` by default to all queries, but when using the `build` method it is not included. Does that makes sense?

**Comment by jeff3yan** [comment]
I think the exclusion filter could remain as a custom filter, since it's not too difficult to initialize before usage in a particular project.

However the custom query builder usage could be addressed in the main package if it's unsupported now. I haven't read the objection docs in a while, but from what I understand a custom query builder is typically attached to a model (or base model).

Is this not applying when you pass it to objection filter? Would you be able to provide a small code example?
